/* automatically generated from xfwm4-tweaks-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tweaks_dialog_ui)
#endif
#ifdef __GNUC__
static const char tweaks_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tweaks_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kAdjustment\" id=\"adjustment1\"><property name=\"upper\">100</property"
  "><property name=\"value\">75</property><property name=\"step_increment\""
  ">1</property><property name=\"page_increment\">10</property></object><o"
  "bject class=\"GtkAdjustment\" id=\"adjustment2\"><property name=\"upper"
  "\">100</property><property name=\"value\">90</property><property name=\""
  "step_increment\">1</property><property name=\"page_increment\">10</prop"
  "erty></object><object class=\"GtkAdjustment\" id=\"adjustment3\"><prope"
  "rty name=\"upper\">100</property><property name=\"value\">90</property>"
  "<property name=\"step_increment\">1</property><property name=\"page_inc"
  "rement\">10</property></object><object class=\"GtkAdjustment\" id=\"adj"
  "ustment4\"><property name=\"upper\">100</property><property name=\"valu"
  "e\">90</property><property name=\"step_increment\">1</property><propert"
  "y name=\"page_increment\">10</property></object><object class=\"GtkAdju"
  "stment\" id=\"adjustment5\"><property name=\"upper\">100</property><pro"
  "perty name=\"value\">90</property><property name=\"step_increment\">1</"
  "property><property name=\"page_increment\">10</property></object><objec"
  "t class=\"GtkAdjustment\" id=\"adjustment6\"><property name=\"upper\">1"
  "00</property><property name=\"value\">90</property><property name=\"ste"
  "p_increment\">1</property><property name=\"page_increment\">10</propert"
  "y></object><object class=\"XfceTitledDialog\" id=\"main-dialog\"><prope"
  "rty name=\"can_focus\">False</property><property name=\"title\" transla"
  "table=\"yes\">Window Manager Tweaks</property><property name=\"window_p"
  "osition\">center-on-parent</property><property name=\"default_height\">"
  "480</property><property name=\"icon_name\">wmtweaks</property><property"
  " name=\"type_hint\">dialog</property><property name=\"subtitle\" transl"
  "atable=\"yes\">Fine-tune window behaviour and effects</property><child "
  "internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"main-vbox\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><child internal-child=\"action_area\"><object class=\"GtkHB"
  "uttonBox\" id=\"dialog-action_area1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "layout_style\">end</property><child><object class=\"GtkButton\" id=\"bu"
  "tton2\"><property name=\"label\">gtk-help</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">True</property><property name=\"use_stock\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty><property name=\"secondary\">True</property></packing></child><chil"
  "d><object class=\"GtkButton\" id=\"button1\"><property name=\"label\">g"
  "tk-close</property><property name=\"use_action_appearance\">False</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">True</property>"
  "<property name=\"use_stock\">True</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"pack_type\">end</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kNotebook\" id=\"plug-child\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"border_wi"
  "dth\">6</property><child><object class=\"GtkVBox\" id=\"vbox1\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"border_width\">12</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkCheckButton\" id=\"cycl"
  "e_minimum_check\"><property name=\"label\" translatable=\"yes\">S_kip w"
  "indows that have \"skip pager\"\nor \"skip taskbar\" properties set</pr"
  "operty><property name=\"use_action_appearance\">False</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"use_underline\">True</property><property name=\"draw_indicator\">"
  "True</property></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"cycle_hidden_check\"><property name=\"label\" translatable=\"yes\""
  ">_Include hidden (i.e. iconified) windows</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild><child><object class=\"GtkCheckButton\" id=\"cycle_workspaces_check"
  "\"><property name=\"label\" translatable=\"yes\">Cycle _through windows"
  " on all workspaces</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">2</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"cycle_draw_frame\"><property name=\"label\" t"
  "ranslatable=\"yes\">_Draw frame around selected windows while cycling</"
  "property><property name=\"use_action_appearance\">False</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">3</property></packing></child></object></child><child type=\"tab\"><ob"
  "ject class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">C_ycling</property><property name=\"use_un"
  "derline\">True</property></object><packing><property name=\"tab_fill\">"
  "False</property></packing></child><child><object class=\"GtkVBox\" id=\""
  "vbox3\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"border_width\">12</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkCheckBut"
  "ton\" id=\"prevent_focus_stealing_check\"><property name=\"label\" tran"
  "slatable=\"yes\">Activate foc_us stealing prevention</property><propert"
  "y name=\"use_action_appearance\">False</property><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"receives_default\">False</property><property name=\"use_under"
  "line\">True</property><property name=\"draw_indicator\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkCheckButton\" id=\"focus_hint"
  "_check\"><property name=\"label\" translatable=\"yes\">Honor _standard "
  "ICCCM focus hint</property><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">1</property></packing></child><child><object class="
  "\"GtkVBox\" id=\"prevent_focus_stealing_box\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"lab"
  "el11\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"xalign\">0</property><property "
  "name=\"label\" translatable=\"yes\">When a window raises itself:</prope"
  "rty></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkAlignment\" id=\"alignment2"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"bottom_padding\">6</property><prope"
  "rty name=\"left_padding\">12</property><child><object class=\"GtkVBox\""
  " id=\"vbox14\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"border_width\">6</prope"
  "rty><property name=\"spacing\">6</property><child><object class=\"GtkRa"
  "dioButton\" id=\"activate_action_bring_option\"><property name=\"label\""
  " translatable=\"yes\">_Bring window on current workspace</property><pro"
  "perty name=\"use_action_appearance\">False</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"use_u"
  "nderline\">True</property><property name=\"active\">True</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkRadioButton\" id=\"activate_action_switch_option\"><prope"
  "rty name=\"label\" translatable=\"yes\">Switch to win_dow\'s workspace<"
  "/property><property name=\"use_action_appearance\">False</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">False</property><propert"
  "y name=\"use_underline\">True</property><property name=\"active\">True<"
  "/property><property name=\"draw_indicator\">True</property><property na"
  "me=\"group\">activate_action_bring_option</property></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child><chil"
  "d><object class=\"GtkRadioButton\" id=\"activate_action_none_option\"><"
  "property name=\"label\" translatable=\"yes\">Do _nothing</property><pro"
  "perty name=\"use_action_appearance\">False</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"use_u"
  "nderline\">True</property><property name=\"active\">True</property><pro"
  "perty name=\"draw_indicator\">True</property><property name=\"group\">a"
  "ctivate_action_bring_option</property></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">2</property></packing></child></object></child></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">2<"
  "/property></packing></child></object><packing><property name=\"position"
  "\">1</property></packing></child><child type=\"tab\"><object class=\"Gt"
  "kLabel\" id=\"label2\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">_Focus</property><property name=\"use_underline\">True</p"
  "roperty></object><packing><property name=\"position\">1</property><prop"
  "erty name=\"tab_fill\">False</property></packing></child><child><object"
  " class=\"GtkVBox\" id=\"vbox4\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"border"
  "_width\">12</property><property name=\"spacing\">6</property><child><ob"
  "ject class=\"GtkHBox\" id=\"hbox1\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"sp"
  "acing\">12</property><child><object class=\"GtkLabel\" id=\"label7\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"xalign\">0</property><property name=\"la"
  "bel\" translatable=\"yes\">Key used to _grab and move windows:</propert"
  "y><property name=\"use_underline\">True</property><property name=\"mnem"
  "onic_widget\">easy_click_combo_box</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkComboBox\" id=\"easy_click_combo_box\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">1</property></p"
  "acking></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"raise_with_any_button_check\"><property name=\"label\" translatabl"
  "e=\"yes\">_Raise windows when any mouse button is pressed</property><pr"
  "operty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"borde"
  "rless_maximize_check\"><property name=\"label\" translatable=\"yes\">Hi"
  "de frame of windows when ma_ximized</property><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">False</property><property name=\"use_underline\">True</prop"
  "erty><property name=\"draw_indicator\">True</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">2</property></packing></child><"
  "child><object class=\"GtkCheckButton\" id=\"restore_on_move_check\"><pr"
  "operty name=\"label\" translatable=\"yes\">Restore original size of max"
  "imi_zed windows when moving</property><property name=\"use_action_appea"
  "rance\">False</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">False</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">3</property></packing></child><child><o"
  "bject class=\"GtkCheckButton\" id=\"tile_on_move_check\"><property name"
  "=\"label\" translatable=\"yes\">Automatically _tile windows when moving"
  " toward the screen edge</property><property name=\"use_action_appearanc"
  "e\">False</property><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"receives_default\">"
  "False</property><property name=\"use_underline\">True</property><proper"
  "ty name=\"draw_indicator\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">4</property></packing></child><child><objec"
  "t class=\"GtkCheckButton\" id=\"urgent_blink\"><property name=\"label\""
  " translatable=\"yes\">Notify of _urgency by making window\'s decoration"
  " blink</property><property name=\"use_action_appearance\">False</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">False</property><"
  "property name=\"use_underline\">True</property><property name=\"draw_in"
  "dicator\">True</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">False</property><property name=\""
  "position\">5</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"snap_resist_check\"><property name=\"label\" translatabl"
  "e=\"yes\">Use _edge resistance instead of window snapping</property><pr"
  "operty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">5</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"repea"
  "t_urgent_blink\"><property name=\"label\" translatable=\"yes\">Keep urg"
  "ent windows _blinking repeatedly</property><property name=\"use_action_"
  "appearance\">False</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"use_underline\">True</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">6</property></packing></child></ob"
  "ject><packing><property name=\"position\">2</property></packing></child"
  "><child type=\"tab\"><object class=\"GtkLabel\" id=\"label3\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label\" translatable=\"yes\">_Accessibility</pr"
  "operty><property name=\"use_underline\">True</property></object><packin"
  "g><property name=\"position\">2</property><property name=\"tab_fill\">F"
  "alse</property></packing></child><child><object class=\"GtkVBox\" id=\""
  "vbox5\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"border_width\">12</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkCheckBut"
  "ton\" id=\"scroll_workspaces_check\"><property name=\"label\" translata"
  "ble=\"yes\">Use the _mouse wheel on the desktop to switch workspaces</p"
  "roperty><property name=\"use_action_appearance\">False</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"toggle_workspaces_check\"><property name=\"label\" translatable=\""
  "yes\">_Remember and recall previous workspace\nwhen switching via keybo"
  "ard shortcuts</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">1</property></packing></child><child><object class=\""
  "GtkCheckButton\" id=\"wrap_layout_check\"><property name=\"label\" tran"
  "slatable=\"yes\">Wrap workspaces depending on the actual desktop _layou"
  "t</property><property name=\"use_action_appearance\">False</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"draw_indicat"
  "or\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">2</property></packing></child><child><object class=\"GtkCheckButt"
  "on\" id=\"wrap_cycle_check\"><property name=\"label\" translatable=\"ye"
  "s\">Wrap workspaces when _the first or the last workspace is reached</p"
  "roperty><property name=\"use_action_appearance\">False</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">3</property></packing></child></object><packing><property name=\"posit"
  "ion\">3</property></packing></child><child type=\"tab\"><object class=\""
  "GtkLabel\" id=\"label4\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">_Workspaces</property><property name=\"use_underline\">"
  "True</property></object><packing><property name=\"position\">3</propert"
  "y><property name=\"tab_fill\">False</property></packing></child><child>"
  "<object class=\"GtkVBox\" id=\"vbox6\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "border_width\">12</property><property name=\"spacing\">6</property><chi"
  "ld><object class=\"GtkLabel\" id=\"label8\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  ">_Minimum size of windows to trigger smart placement:</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"mnemonic_widg"
  "et\">placement_ratio_scale</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkAlignment\" id=\"alignment4\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"b"
  "ottom_padding\">6</property><property name=\"left_padding\">12</propert"
  "y><child><object class=\"GtkHBox\" id=\"hbox2\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\""
  "label9\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\" "
  "comments=\"Smart placement size\">&lt;i&gt;Small&lt;/i&gt;</property><p"
  "roperty name=\"use_markup\">True</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkHScale\" id=\"placement_ratio_scale\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"adjustment\">adjustment1</property><property name=\"restri"
  "ct_to_fill_level\">False</property><property name=\"draw_value\">False<"
  "/property></object><packing><property name=\"expand\">True</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child><child><object class=\"GtkLabel\" id=\"label10\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\" comments"
  "=\"Smart placement size\">&lt;i&gt;Large&lt;/i&gt;</property><property "
  "name=\"use_markup\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">2</property></packing></child></object></child></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">1</property></pack"
  "ing></child><child><object class=\"GtkVBox\" id=\"default_placement_box"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"spacing\">6</property><child><objec"
  "t class=\"GtkLabel\" id=\"label27\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"xa"
  "lign\">0</property><property name=\"label\" translatable=\"yes\">By def"
  "ault, place windows:</property></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">0</property></packing></child><child><object class=\"Gtk"
  "Alignment\" id=\"alignment10\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"bottom_"
  "padding\">6</property><property name=\"left_padding\">12</property><chi"
  "ld><object class=\"GtkVBox\" id=\"vbox18\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"border_width\">6</property><property name=\"spacing\">6</property>"
  "<child><object class=\"GtkRadioButton\" id=\"placement_center_option\">"
  "<property name=\"label\" translatable=\"yes\">At the c_enter of the scr"
  "een</property><property name=\"use_action_appearance\">False</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"use_underline\">True</property><property name=\"draw_indic"
  "ator\">True</property></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkRadioButt"
  "on\" id=\"placement_mouse_option\"><property name=\"label\" translatabl"
  "e=\"yes\">U_nder the mouse pointer</property><property name=\"use_actio"
  "n_appearance\">False</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"active\">True</property><property name=\"draw_indi"
  "cator\">True</property><property name=\"group\">placement_center_option"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child></object></child></object><packing><property n"
  "ame=\"expand\">True</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">1</property></packing></child></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">2</property></packing></child"
  "></object><packing><property name=\"position\">4</property></packing></"
  "child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label5\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">_Placement</p"
  "roperty><property name=\"use_underline\">True</property></object><packi"
  "ng><property name=\"position\">4</property><property name=\"tab_fill\">"
  "False</property></packing></child><child><object class=\"GtkVBox\" id=\""
  "vbox7\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"border_width\">12</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkCheckBut"
  "ton\" id=\"use_compositing_check\"><property name=\"label\" translatabl"
  "e=\"yes\">_Enable display compositing</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkScrolledWindow\" id=\"use_compositing_box\">"
  "<property name=\"visible\">True</property><property name=\"sensitive\">"
  "False</property><property name=\"can_focus\">True</property><property n"
  "ame=\"hscrollbar_policy\">never</property><property name=\"vscrollbar_p"
  "olicy\">automatic</property><child><object class=\"GtkViewport\" id=\"v"
  "iewport1\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"resize_mode\">queue</proper"
  "ty><property name=\"shadow_type\">none</property><child><object class=\""
  "GtkAlignment\" id=\"alignment3\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"botto"
  "m_padding\">6</property><property name=\"left_padding\">12</property><c"
  "hild><object class=\"GtkVBox\" id=\"vbox8\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"spacing\">6</property><child><object class=\"GtkCheckButton\" id="
  "\"unredirect_overlays_check\"><property name=\"label\" translatable=\"y"
  "es\">Display _fullscreen overlay windows directly</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">0</property></packi"
  "ng></child><child><object class=\"GtkCheckButton\" id=\"sync_to_vblank_"
  "check\"><property name=\"label\" translatable=\"yes\">Synchronize drawi"
  "ng to the _vertical blank</property><property name=\"use_action_appeara"
  "nce\">False</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkCheckButton\" id=\"show_popup_shadow_check\"><property nam"
  "e=\"label\" translatable=\"yes\">Show shadows under pop_up windows</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">2"
  "</property></packing></child><child><object class=\"GtkCheckButton\" id"
  "=\"show_dock_shadow_check\"><property name=\"label\" translatable=\"yes"
  "\">Show shadows under _dock windows</property><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">False</property><property name=\"use_underline\">True</prop"
  "erty><property name=\"draw_indicator\">True</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">3</property></packing></child><c"
  "hild><object class=\"GtkCheckButton\" id=\"show_frame_shadow_check\"><p"
  "roperty name=\"label\" translatable=\"yes\">Show shadows under _regular"
  " windows</property><property name=\"use_action_appearance\">False</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">False</property"
  "><property name=\"use_underline\">True</property><property name=\"draw_"
  "indicator\">True</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">True</property><property name=\""
  "position\">4</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label12\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"xalign\">0</propert"
  "y><property name=\"label\" translatable=\"yes\">Opaci_ty of window deco"
  "rations:</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"mnemonic_widget\">frame_opacity_scale</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">5</property></packing></c"
  "hild><child><object class=\"GtkAlignment\" id=\"alignment5\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"top_padding\">2</property><property name=\"left_"
  "padding\">12</property><child><object class=\"GtkHBox\" id=\"hbox3\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><child><object class=\"GtkLabel\" id=\"label17\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label\" translatable=\"yes\">&lt;i&gt;Transpar"
  "ent&lt;/i&gt;</property><property name=\"use_markup\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">0</property></pa"
  "cking></child><child><object class=\"GtkHScale\" id=\"frame_opacity_sca"
  "le\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"update_policy\">discontinuous</pro"
  "perty><property name=\"adjustment\">adjustment2</property><property nam"
  "e=\"restrict_to_fill_level\">False</property><property name=\"draw_valu"
  "e\">False</property></object><packing><property name=\"expand\">True</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">1</property></packing></child><child><object class=\"GtkLabel\" id="
  "\"label18\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_markup\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">2"
  "</property></packing></child></object></child></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">6</property></packing></child><child><o"
  "bject class=\"GtkLabel\" id=\"label13\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"xalign\">0</property><property name=\"label\" translatable=\"yes\">Op"
  "acity of _inactive windows:</property><property name=\"use_underline\">"
  "True</property><property name=\"mnemonic_widget\">inactive_opacity_scal"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">7<"
  "/property></packing></child><child><object class=\"GtkAlignment\" id=\""
  "alignment6\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"top_padding\">2</property>"
  "<property name=\"left_padding\">12</property><child><object class=\"Gtk"
  "HBox\" id=\"hbox4\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><child><object class=\"GtkLabel\" i"
  "d=\"label19\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">&lt;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_mark"
  "up\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkHScale\" "
  "id=\"inactive_opacity_scale\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"update_po"
  "licy\">discontinuous</property><property name=\"adjustment\">adjustment"
  "3</property><property name=\"restrict_to_fill_level\">False</property><"
  "property name=\"draw_value\">False</property></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">1</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"label20\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><proper"
  "ty name=\"use_markup\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"position\">2</property></packing></child></object></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">8</property></"
  "packing></child><child><object class=\"GtkLabel\" id=\"label14\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"xalign\">0</property><property name=\"label\""
  " translatable=\"yes\">Opacity of windows during _move:</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"mnemonic_wid"
  "get\">move_opacity_scale</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">9</property></packing></child><child><object class"
  "=\"GtkAlignment\" id=\"alignment7\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"to"
  "p_padding\">2</property><property name=\"left_padding\">12</property><c"
  "hild><object class=\"GtkHBox\" id=\"hbox5\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><child><obj"
  "ect class=\"GtkLabel\" id=\"label21\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</property><"
  "property name=\"use_markup\">True</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkHScale\" id=\"move_opacity_scale\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"update_policy\">discontinuous</property><property name=\"adj"
  "ustment\">adjustment4</property><property name=\"restrict_to_fill_level"
  "\">False</property><property name=\"draw_value\">False</property></obje"
  "ct><packing><property name=\"expand\">True</property><property name=\"f"
  "ill\">True</property><property name=\"position\">1</property></packing>"
  "</child><child><object class=\"GtkLabel\" id=\"label22\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&g"
  "t;</property><property name=\"use_markup\">True</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">2</property></packing></chi"
  "ld></object></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">10</property></packing></child><child><object class=\"GtkLabel\" "
  "id=\"label15\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"xalign\">0</property><p"
  "roperty name=\"label\" translatable=\"yes\">Opacity of windows during r"
  "esi_ze:</property><property name=\"use_underline\">True</property><prop"
  "erty name=\"mnemonic_widget\">resize_opacity_scale</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">11</property></packing><"
  "/child><child><object class=\"GtkAlignment\" id=\"alignment8\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"top_padding\">2</property><property name=\"lef"
  "t_padding\">12</property><child><object class=\"GtkHBox\" id=\"hbox6\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><child><object class=\"GtkLabel\" id=\"label23\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">&lt;i&gt;Transp"
  "arent&lt;/i&gt;</property><property name=\"use_markup\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkHScale\" id=\"resize_opacity_"
  "scale\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"update_policy\">discontinuous</"
  "property><property name=\"adjustment\">adjustment5</property><property "
  "name=\"restrict_to_fill_level\">False</property><property name=\"draw_v"
  "alue\">False</property></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">1</property></packing></child><child><object class=\"GtkLabel\" "
  "id=\"label24\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_markup\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">2</property></packing></child></object></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">12</property></packing></child><child"
  "><object class=\"GtkLabel\" id=\"label16\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  ">Opacity of popup wi_ndows:</property><property name=\"use_underline\">"
  "True</property><property name=\"mnemonic_widget\">popup_opacity_scale</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">13</p"
  "roperty></packing></child><child><object class=\"GtkAlignment\" id=\"al"
  "ignment9\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"top_padding\">2</property><"
  "property name=\"left_padding\">12</property><child><object class=\"GtkH"
  "Box\" id=\"hbox7\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><child><object class=\"GtkLabel\" id"
  "=\"label25\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">&lt;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkHScale\" id"
  "=\"popup_opacity_scale\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"update_policy\""
  ">discontinuous</property><property name=\"adjustment\">adjustment6</pro"
  "perty><property name=\"restrict_to_fill_level\">False</property><proper"
  "ty name=\"draw_value\">False</property></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child><child><object cla"
  "ss=\"GtkLabel\" id=\"label26\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property nam"
  "e=\"use_markup\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">2</property></packing></child></object></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">14</property></packi"
  "ng></child></object></child></object></child></object></child></object>"
  "<packing><property name=\"expand\">True</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild></object><packing><property name=\"position\">5</property></packin"
  "g></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label6\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label\" translatable=\"yes\">C_omposit"
  "or</property><property name=\"use_underline\">True</property></object><"
  "packing><property name=\"position\">5</property><property name=\"tab_fi"
  "ll\">False</property></packing></child></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child></object></child><"
  "action-widgets><action-widget response=\"-11\">button2</action-widget><"
  "action-widget response=\"0\">button1</action-widget></action-widgets></"
  "object></interface>"
};

static const unsigned tweaks_dialog_ui_length = 43429u;

